version: '3.8'
services:
  am1:
    image: prom/alertmanager:v0.25.0
    volumes:
      - $PWD/am1/:/alertmanager/
      - $PWD/config/alertmanager.yml:/alertmanager.yml
    ports:
      - 9001:9093
    command:
      [
        "--config.file=/alertmanager.yml",
        "--storage.path=/alertmanager/data/",
        "--cluster.peer=am1:9094",
        "--cluster.peer=am2:9094",
        "--cluster.peer=am3:9094"
      ]
    networks:
      monnet:
        aliases:
          - am1

  am2:
    image: prom/alertmanager:v0.25.0
    volumes:
      - $PWD/am2/:/alertmanager/
      - $PWD/config/alertmanager.yml:/alertmanager.yml
    ports:
      - 9002:9093
    command:
      [
        "--config.file=/alertmanager.yml",
        "--storage.path=/alertmanager/data/",
        "--cluster.peer=am1:9094",
        "--cluster.peer=am2:9094",
        "--cluster.peer=am3:9094"
      ]
    networks:
      monnet:
        aliases:
          - am2

  am3:
    image: prom/alertmanager:v0.25.0
    volumes:
      - $PWD/am3/:/alertmanager/
      - $PWD/config/alertmanager.yml:/alertmanager.yml
    ports:
      - 9003:9093
    command:
      [
        "--config.file=/alertmanager.yml",
        "--storage.path=/alertmanager/data/",
        "--cluster.peer=am1:9094",
        "--cluster.peer=am2:9094",
        "--cluster.peer=am3:9094"
      ]
    networks:
      monnet:
        aliases:
          - am3

  prometheus:
    image: prom/prometheus:v2.46.0
    volumes:
      - $PWD/prometheus/:/prometheus/
      - $PWD/config/prometheus.yml:/prometheus.yml
      - $PWD/config/prometheus-rules.yml:/prometheus-rules.yml
    ports:
      - 9090:9090
    command:
      [
        "--config.file=/prometheus.yml",
        "--storage.tsdb.path=/prometheus/data",
        "--web.enable-lifecycle"
      ]
    networks:
      monnet:
        aliases:
          - prometheus

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.23.0
    volumes:
      - $PWD/config/blackbox.yml:/blackbox.yml
    ports:
      - 9115:9115
    command: [ "--config.file=/blackbox.yml" ]
    networks:
      monnet:
        aliases:
          - blackbox-exporter

  ehko:
    image: mikejoh/ehko:latest
    ports:
      - 5001:5001
    networks:
      monnet:
        aliases:
          - ehko

networks:
  monnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.250.0/24
