global:
  scrape_interval: 15s # Set the scrape interval. Default is every 1 minute.
  evaluation_interval: 15s # Set the rule evaluate interval. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

rule_files:
  - /prometheus-rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "am1:9093"
            - "am2:9093"
            - "am3:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: blackbox
    metrics_path: /metrics
    static_configs:
      - targets:
          - blackbox-exporter:9115

  - job_name: blackbox-http-checks
    honor_timestamps: true
    params:
      module: [http_2xx]
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /probe
    scheme: http
    static_configs:
      - targets:
          - https://www.google.com
          - http://ehko:5001/responder/401
          - http://ehko:5001/responder/200
          - http://ehko:5001/responder/500
    relabel_configs:
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        target_label: __param_target
        replacement: $1
        action: replace
      - source_labels: [__param_target]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: localhost:9115
        action: replace
      - separator: ;
        regex: (.*)
        target_label: job
        replacement: blackbox-exporter
        action: replace
